# Generated by Django 5.0.6 on 2024-05-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aplicacion',
            fields=[
                ('id_aplicaciones', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('foto_portada', models.ImageField(default='images/transparent.png', upload_to='images/albums/')),
            ],
        ),
    ]
