# Generated by Django 5.0.6 on 2024-05-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplicacion',
            old_name='name',
            new_name='nombre',
        ),
    ]
