# Generated by Django 5.0.6 on 2024-05-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probest', '0002_rename_name_aplicacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='url',
            field=models.CharField(default='/', max_length=40),
        ),
    ]
